const WAVENET_FEMALE_GERMAN_1 = 'de-DE-Wavenet-A';
const WAVENET_FEMALE_GERMAN_2 = 'de-DE-Wavenet-C';
const WAVENET_FEMALE_GERMAN_3 = 'de-DE-Wavenet-F';
const WAVENET_MALE_GERMAN_1 = 'de-DE-Wavenet-B';
const WAVENET_MALE_GERMAN_2 = 'de-DE-Wavenet-D';
const WAVENET_MALE_GERMAN_3 = 'de-DE-Wavenet-E';

const STANDARD_FEMALE_GERMAN_1 = 'de-DE-Standard-A';
const STANDARD_FEMALE_GERMAN_2 = 'de-DE-Standard-C';
const STANDARD_FEMALE_GERMAN_3 = 'de-DE-Standard-F';
const STANDARD_MALE_GERMAN_1 = 'de-DE-Standard-B';
const STANDARD_MALE_GERMAN_2 = 'de-DE-Standard-D';
const STANDARD_MALE_GERMAN_3 = 'de-DE-Standard-E';

const STANDARD_FEMALE_ENGLISH_1 = 'en-US-Standard-A';
const STANDARD_FEMALE_ENGLISH_2 = 'en-US-Standard-C';
const STANDARD_FEMALE_ENGLISH_3 = 'en-US-Standard-F';
const STANDARD_MALE_ENGLISH_1 = 'en-US-Standard-B';
const STANDARD_MALE_ENGLISH_2 = 'en-US-Standard-D';
const STANDARD_MALE_ENGLISH_3 = 'en-US-Standard-E';

const WAVENET_FEMALE_ENGLISH_1 = 'en-US-Wavenet-A';
const WAVENET_FEMALE_ENGLISH_2 = 'en-US-Wavenet-C';
const WAVENET_FEMALE_ENGLISH_3 = 'en-US-Wavenet-F';
const WAVENET_MALE_ENGLISH_1 = 'en-US-Wavenet-B';
const WAVENET_MALE_ENGLISH_2 = 'en-US-Wavenet-D';
const WAVENET_MALE_ENGLISH_3 = 'en-US-Wavenet-E';

export const VOICES = {
  WAVENET_FEMALE_ENGLISH_1,
  WAVENET_FEMALE_ENGLISH_2,
  WAVENET_FEMALE_ENGLISH_3,
  WAVENET_MALE_ENGLISH_1,
  WAVENET_MALE_ENGLISH_2,
  WAVENET_MALE_ENGLISH_3,
  STANDARD_FEMALE_ENGLISH_1,
  STANDARD_FEMALE_ENGLISH_2,
  STANDARD_FEMALE_ENGLISH_3,
  STANDARD_MALE_ENGLISH_1,
  STANDARD_MALE_ENGLISH_2,
  STANDARD_MALE_ENGLISH_3,
  STANDARD_FEMALE_GERMAN_1,
  STANDARD_FEMALE_GERMAN_2,
  STANDARD_FEMALE_GERMAN_3,
  STANDARD_MALE_GERMAN_1,
  STANDARD_MALE_GERMAN_2,
  STANDARD_MALE_GERMAN_3,
  WAVENET_FEMALE_GERMAN_1,
  WAVENET_FEMALE_GERMAN_2,
  WAVENET_FEMALE_GERMAN_3,
  WAVENET_MALE_GERMAN_1,
  WAVENET_MALE_GERMAN_2,
  WAVENET_MALE_GERMAN_3,
};
